name: iOS Build
on: [push, pull_request]

jobs:
  build:
    name: Build and upload counter.
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-12'
            version: '14.2'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Flutter Build 
        run: flutter build ios --release --no-codesign

      - name: Strip Debug Symbols
        run: |
          cd /Users/runner/work/Counter-Super-Simple-Rewrite/Counter-Super-Simple-Rewrite/build/ios/iphoneos/Runner.app
          find . -name "*.dSYM" -exec rm -rf {} \;
        
      - name: Convert to IPA 1
        run: mkdir -p Payload
             
      - name: Convert to IPA 2
        run: cp -R /Users/runner/work/Counter-Super-Simple-Rewrite/Counter-Super-Simple-Rewrite/build/ios/iphoneos/Runner.app Payload/

      - name: Convert to IPA 3
        run: zip -r Counter.ipa Payload

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS Build
          path: ./Counter.ipa