name: Windows Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Windows Application
        run: flutter build windows --release

      # Corrected path to build output
      - name: List Build Directory
        run: dir build/windows/x64/runner/Release/

      # Corrected path for uploading the build artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/
